"""
synth_engine.py
A simple educational polyphonic subtractive synth engine.

Provides:
- Oscillator (sine, square, saw, triangle)
- ADSR envelope
- Simple one-pole low-pass filter (per-voice)
- Voice management for polyphony
- Buffer-based render() interface that returns stereo float32 frames

Author: generated by ChatGPT for user
"""
import numpy as np

SAMPLE_RATE = 44100

_note_to_freq_cache = {}
def midi_note_to_freq(note):
    # 69 -> 440Hz
    if note in _note_to_freq_cache:
        return _note_to_freq_cache[note]
    freq = 440.0 * (2.0 ** ((note - 69) / 12.0))
    _note_to_freq_cache[note] = freq
    return freq

class Oscillator:
    def __init__(self, waveform='sine', sample_rate=SAMPLE_RATE):
        self.waveform = waveform
        self.sample_rate = sample_rate
        self.phase = 0.0

    def set_waveform(self, w):
        self.waveform = w

    def process(self, frequency, frames):
        # returns a numpy array of length frames
        t = (np.arange(frames) + 0.0) / self.sample_rate
        phase_inc = (2.0 * np.pi * frequency) / self.sample_rate
        phases = self.phase + phase_inc * np.arange(frames)
        self.phase = (phases[-1] + phase_inc) % (2.0 * np.pi)
        if self.waveform == 'sine':
            return np.sin(phases)
        elif self.waveform == 'square':
            return np.sign(np.sin(phases))
        elif self.waveform == 'saw':
            # naive saw: map phase [-pi, pi] to [-1,1]
            return 2.0 * (phases / (2.0 * np.pi) - np.floor(phases / (2.0 * np.pi) + 0.5))
        elif self.waveform == 'triangle':
            return 2.0 * np.abs(2.0 * (phases / (2.0 * np.pi) - np.floor(phases / (2.0 * np.pi) + 0.5))) - 1.0
        else:
            return np.sin(phases)

class ADSR:
    def __init__(self, attack=0.01, decay=0.1, sustain=0.7, release=0.2, sample_rate=SAMPLE_RATE):
        self.attack = max(1e-6, attack)
        self.decay = decay
        self.sustain = sustain
        self.release = release
        self.sample_rate = sample_rate
        self.state = 'idle'
        self.level = 0.0
        self.time = 0.0
        self.note_on_time = 0.0
        self.note_off_time = None

    def note_on(self):
        self.state = 'attack'
        self.time = 0.0
        self.note_off_time = None

    def note_off(self):
        self.state = 'release'
        self.time = 0.0

    def process(self, frames):
        out = np.zeros(frames, dtype=np.float32)
        for i in range(frames):
            if self.state == 'attack':
                self.level += 1.0 / max(1, int(self.attack * self.sample_rate))
                if self.level >= 1.0:
                    self.level = 1.0
                    self.state = 'decay'
            elif self.state == 'decay':
                self.level -= (1.0 - self.sustain) / max(1, int(self.decay * self.sample_rate))
                if self.level <= self.sustain:
                    self.level = self.sustain
                    self.state = 'sustain'
            elif self.state == 'sustain':
                # hold sustain
                self.level = self.sustain
            elif self.state == 'release':
                self.level -= self.sustain / max(1, int(self.release * self.sample_rate))
                if self.level <= 0.0:
                    self.level = 0.0
                    self.state = 'idle'
            elif self.state == 'idle':
                self.level = 0.0
            out[i] = self.level
        return out

class OnePoleLP:
    def __init__(self, cutoff=1000.0, sample_rate=SAMPLE_RATE):
        self.cutoff = cutoff
        self.sample_rate = sample_rate
        self.z = 0.0
        self.calculate_coeff()

    def calculate_coeff(self):
        # simple RC low-pass one-pole
        x = np.exp(-2.0 * np.pi * self.cutoff / self.sample_rate)
        self.a0 = 1.0 - x
        self.b1 = x

    def set_cutoff(self, cutoff):
        self.cutoff = max(20.0, min(cutoff, self.sample_rate * 0.45))
        self.calculate_coeff()

    def process(self, x):
        # x: numpy array
        y = np.zeros_like(x)
        for i, xi in enumerate(x):
            self.z = self.a0 * xi + self.b1 * self.z
            y[i] = self.z
        return y

class Voice:
    def __init__(self, sample_rate=SAMPLE_RATE):
        self.sample_rate = sample_rate
        self.osc1 = Oscillator('saw', sample_rate)
        self.osc2 = Oscillator('sine', sample_rate)
        self.envelope = ADSR()
        self.filter = OnePoleLP(5000.0, sample_rate)
        self.note = None
        self.velocity = 0.0
        self.active = False
        self.detune = 0.0

    def note_on(self, note, velocity):
        self.note = note
        self.velocity = velocity / 127.0
        self.active = True
        self.envelope.note_on()
        self.osc1.phase = 0.0
        self.osc2.phase = 0.0

    def note_off(self):
        self.envelope.note_off()

    def is_done(self):
        return (not self.active) or (self.envelope.state == 'idle' and self.envelope.level == 0.0)

    def render(self, frames, lfo_value=0.0, detune_cents=0.0, filter_env_amount=0.0):
        if not self.active:
            return np.zeros((frames,), dtype=np.float32)
        freq = midi_note_to_freq(self.note) * (2.0 ** (detune_cents / 1200.0))
        # basic LFO applied as pitch bend (small)
        freq = freq * (1.0 + lfo_value * 0.01)
        osc1 = self.osc1.process(freq, frames)
        osc2 = self.osc2.process(freq * (1.0 + self.detune), frames)
        mix = 0.6 * osc1 + 0.4 * osc2
        # envelope
        env = self.envelope.process(frames)
        # simple envelope -> filter cutoff modulation
        base_cutoff = self.filter.cutoff
        cutoff_env = base_cutoff + filter_env_amount * env * 2000.0
        self.filter.set_cutoff(cutoff_env.mean())
        filtered = self.filter.process(mix)
        out = filtered * env * self.velocity
        # if envelope finished, deactivate voice
        if self.envelope.state == 'idle' and self.envelope.level == 0.0:
            self.active = False
        return out

class SynthEngine:
    def __init__(self, sample_rate=SAMPLE_RATE, polyphony=8):
        self.sample_rate = sample_rate
        self.voices = [Voice(sample_rate) for _ in range(polyphony)]
        self.lfo_phase = 0.0
        self.lfo_rate = 5.0
        self.master_gain = 0.2
        self.filter_env_amount = 0.0

    def note_on(self, note, velocity=100):
        # allocate free voice or steal the oldest
        for v in self.voices:
            if not v.active:
                v.note_on(note, velocity)
                return
        # steal voice 0 if none free
        self.voices[0].note_on(note, velocity)

    def note_off(self, note):
        for v in self.voices:
            if v.active and v.note == note:
                v.note_off()

    def render(self, frames):
        # produce mono and return stereo interleaved
        buffer = np.zeros(frames, dtype=np.float32)
        # simple LFO value for this buffer
        phase_inc = 2.0 * np.pi * self.lfo_rate / self.sample_rate
        phases = self.lfo_phase + phase_inc * np.arange(frames)
        self.lfo_phase = (phases[-1] + phase_inc) % (2.0 * np.pi)
        lfo = np.sin(phases)
        lfo_value = lfo.mean()
        for v in self.voices:
            buffer += v.render(frames, lfo_value=lfo_value, filter_env_amount=self.filter_env_amount)
        # apply master gain and make stereo
        buffer *= self.master_gain
        stereo = np.vstack((buffer, buffer)).T.astype(np.float32)
        return stereo
